# Generated by Django 4.0.1 on 2022-02-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_slot_id_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='slug',
            field=models.SlugField(default='', max_length=260),
        ),
    ]
