# Generated by Django 4.0.1 on 2022-02-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_alter_slot_id_bike'),
    ]

    operations = [
     
    ]
