# Generated by Django 4.0.1 on 2022-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_slot_slot_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_state',
            field=models.CharField(default='Ocupado', max_length=200),
        ),
    ]
