# Generated by Django 4.0.1 on 2022-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_slot_slot_state'),
    ]

    operations = [
     
    ]
