# Generated by Django 4.0.1 on 2022-02-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_alter_slot_id_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_state',
            field=models.CharField(default='Ocupado', max_length=200),
        ),
    ]
