# Generated by Django 4.0.1 on 2022-02-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_alter_slot_id_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='state_station',
            field=models.CharField(default='Disponible', max_length=200),
        ),
    ]
