# Generated by Django 4.0.1 on 2022-02-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='state',
            field=models.CharField(default='Leida', max_length=500),
        ),
    ]
