# Generated by Django 4.0.1 on 2022-02-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0016_incident_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='state',
            field=models.CharField(default='No Leida', max_length=500),
        ),
    ]
