# Generated by Django 4.0.1 on 2022-02-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_profile_id'),
        ('bikes', '0003_alter_bike_station'),
        ('stations', '0004_alter_slot_id_bike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(default='00:00', max_length=10, verbose_name='hour')),
                ('day', models.CharField(default='00-00-00', max_length=10, verbose_name='day')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bike')),
                ('station', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
