# Generated by Django 4.0.1 on 2022-02-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_alter_bike_station'),
        ('rents', '0003_alter_rent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bikes.bike'),
        ),
    ]
