# Generated by Django 4.0.1 on 2022-02-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0005_alter_rent_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='day',
            field=models.CharField(blank=True, default='00-00-00', max_length=10, null=True, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='hour',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='hour'),
        ),
    ]
