# Generated by Django 4.0.1 on 2022-02-10 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0006_alter_rent_day_alter_rent_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.RemoveField(
            model_name='rent',
            name='day',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='hour',
        ),
        migrations.AddField(
            model_name='rent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
