# Generated by Django 4.0.1 on 2022-02-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_id'),
        ('bikes', '0003_alter_bike_station'),
        ('stations', '0012_slot_slot_state'),
        ('rents', '0008_alter_rent_bike_alter_rent_station_alter_rent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='bike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='bikes.bike'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profiles.profile'),
        ),
    ]
