# Generated by Django 4.0.1 on 2022-01-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_state_alter_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(default='Disponible', max_length=200),
        ),
    ]
