# Generated by Django 4.0.1 on 2022-01-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='title',
            new_name='available',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='description',
        ),
        migrations.AddField(
            model_name='bike',
            name='station',
            field=models.CharField(default='Ayuntamiento', max_length=200),
        ),
    ]
