# Generated by Django 4.0.1 on 2022-02-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.CharField(default='No leído', max_length=500),
        ),
    ]
