# Generated by Django 4.0.1 on 2022-02-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_id'),
        ('notifications', '0004_rename_user_notification_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
