# Generated by Django 4.0.1 on 2022-01-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(default='Ayuntamiento', max_length=200)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
    ]
