# Generated by Django 4.0.1 on 2022-01-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='state',
            field=models.CharField(default='Disponible', max_length=200),
        ),
    ]
